/**
 * Project auto-detection for `ctxkit init --auto`: derive build/test
 * commands and module boundaries from what the repo itself declares
 * (package.json, pytest.ini, Cargo.toml, ...). Everything emitted is
 * verifiable fact, never guesswork — the human still reviews the draft.
 */
import { existsSync, readFileSync } from "node:fs";
import { extname, join } from "node:path";
import type { CtxConfig } from "./config.js";
import { walkFiles } from "./fs.js";
import { SOURCE_EXTENSIONS } from "../adapters/symbols.js";

export interface Detected {
  /** Markdown bullet lines for the AGENTS.md Commands section. */
  commands: string[];
  /** Suggested module name -> glob patterns. */
  modules: Record<string, string[]>;
}

const SCRIPT_KEYS = ["build", "dev", "test", "lint"] as const;

function detectCommandsIn(root: string, dir: string): string[] {
  const out: string[] = [];
  const prefix = dir === "." ? "" : `cd ${dir} && `;
  const at = (f: string) => join(root, dir, f);

  const pkgPath = at("package.json");
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
      for (const key of SCRIPT_KEYS) {
        if (pkg.scripts?.[key]) {
          const cmd = key === "test" ? "npm test" : `npm run ${key}`;
          out.push(`- ${capitalize(key)} (js): \`${prefix}${cmd}\` (${pkg.scripts[key]})`);
        }
      }
    } catch {
      /* unparsable package.json — skip */
    }
  }
  if (existsSync(at("pytest.ini")) || existsSync(at("setup.cfg"))) {
    out.push(`- Test (python): \`${prefix}pytest\``);
  } else if (existsSync(at("pyproject.toml"))) {
    const py = readFileSync(at("pyproject.toml"), "utf8");
    if (py.includes("[tool.pytest")) out.push(`- Test (python): \`${prefix}pytest\``);
  }
  if (existsSync(at("Cargo.toml"))) {
    out.push(`- Test (rust): \`${prefix}cargo test\``, `- Build (rust): \`${prefix}cargo build\``);
  }
  if (existsSync(at("go.mod"))) {
    out.push(`- Test (go): \`${prefix}go test ./...\``);
  }
  if (existsSync(at("Makefile"))) {
    out.push(`- Make targets: see \`${dir === "." ? "Makefile" : `${dir}/Makefile`}\``);
  }
  return out;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const CONTAINER_DIRS = new Set(["services", "apps", "packages", "crates", "src", "lib"]);

export function detectProject(config: CtxConfig): Detected {
  const root = config.root;
  const sources = walkFiles(root, { exclude: config.exclude }).filter((f) =>
    SOURCE_EXTENSIONS.has(extname(f)),
  );

  // Commands: repo root, direct children, and children of container dirs.
  const dirs = new Set<string>(["."]);
  for (const f of sources) {
    const parts = f.split("/");
    if (parts.length > 1) dirs.add(parts[0]);
    if (parts.length > 2 && CONTAINER_DIRS.has(parts[0])) dirs.add(`${parts[0]}/${parts[1]}`);
  }
  const commands: string[] = [];
  for (const dir of [...dirs].sort()) commands.push(...detectCommandsIn(root, dir));

  // Modules: group source files by their first one or two path segments.
  const groupCounts = new Map<string, number>();
  for (const f of sources) {
    const parts = f.split("/");
    let group: string;
    if (parts.length === 1) continue; // root-level files: no module
    group =
      CONTAINER_DIRS.has(parts[0]) && parts.length > 2 ? `${parts[0]}/${parts[1]}` : parts[0];
    groupCounts.set(group, (groupCounts.get(group) ?? 0) + 1);
  }
  const modules: Record<string, string[]> = {};
  const top = [...groupCounts.entries()]
    .filter(([, n]) => n >= 3)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);
  for (const [group] of top) {
    const name = group.split("/").pop()!.replace(/[^A-Za-z0-9_-]/g, "-");
    if (!modules[name]) modules[name] = [`${group}/**`];
  }
  return { commands, modules };
}

/** Render a tailored context.config.yaml for `init --auto`. */
export function renderConfig(detected: Detected): string {
  let modulesYaml = "modules: {}\n";
  const names = Object.keys(detected.modules);
  if (names.length > 0) {
    modulesYaml = "modules:\n";
    for (const name of names) {
      modulesYaml += `  ${name}:\n`;
      for (const glob of detected.modules[name]) modulesYaml += `    - "${glob}"\n`;
    }
  }
  return (
    `# ctxkit configuration (schema v1) — generated by \`ctxkit init --auto\`; review and edit.\n` +
    `version: 1\n\n` +
    `# Auto-detected module boundaries (by source file distribution).\n` +
    modulesYaml +
    `\nexclude: []\n\n` +
    `profiles:\n` +
    `  frontier: { inject: [agents], budget: 4000 }\n` +
    `  mid:      { inject: [agents, repomap], budget: 24000 }\n` +
    `  light:    { inject: [agents-summary, repomap, target-files], budget: 12000 }\n\n` +
    `sync:\n  targets: [claude]\n`
  );
}

/** Render a tailored AGENTS.md draft for `init --auto`. */
export function renderAgents(detected: Detected): string {
  const commands =
    detected.commands.length > 0 ? detected.commands.join("\n") : "- Build: `TODO`\n- Test: `TODO`";
  return `# AGENTS.md

<!-- Draft by \`ctxkit init --auto\` — commands below were detected from the
     repo's own manifests; VERIFY them, then fill the rest. Keep under 150
     lines; only what an agent cannot infer from code. -->

## Commands

${commands}

## Architecture decisions

- TODO (the "why" behind non-obvious structure; link ADRs)

## Constraints

- TODO (files not to touch, deployment rules, invariants)

## Domain glossary

| Code | Meaning |
|---|---|
| TODO | TODO |
`;
}
