/**
 * Rule distribution (`ctxkit sync`): AGENTS.md is the single source of
 * truth; per-tool files are generated copies (or symlinks with --link).
 *
 * Implemented internally with zero dependencies — the Ruler adapter can
 * replace this behind the same interface if 30+ targets are ever needed.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import type { CtxConfig } from "./config.js";

export const SYNC_TARGETS: Record<string, string> = {
  claude: "CLAUDE.md",
  cursor: ".cursorrules",
  gemini: "GEMINI.md",
  copilot: ".github/copilot-instructions.md",
  windsurf: ".windsurfrules",
};

const GENERATED_MARK = "<!-- generated by ctxkit sync";
const HEADER =
  `${GENERATED_MARK} from AGENTS.md — edit AGENTS.md and re-run \`ctxkit sync\`; do not edit this file -->\n\n`;

export function expectedContent(agents: string): string {
  return HEADER + agents;
}

export interface SyncAction {
  target: string;
  path: string;
  action: "written" | "linked" | "unchanged" | "skipped-foreign";
}

export interface SyncOptions {
  link?: boolean;
  force?: boolean;
}

function resolveTargets(config: CtxConfig): Array<[string, string]> {
  const names = config.sync?.targets ?? ["claude"];
  const pairs: Array<[string, string]> = [];
  for (const name of names) {
    const file = SYNC_TARGETS[name];
    if (!file) {
      throw new Error(
        `unknown sync target "${name}" — supported: ${Object.keys(SYNC_TARGETS).join(", ")}`,
      );
    }
    pairs.push([name, file]);
  }
  return pairs;
}

function isLinkToAgents(destPath: string, agentsPath: string): boolean {
  try {
    return realpathSync(destPath) === realpathSync(agentsPath);
  } catch {
    return false;
  }
}

export function syncRules(config: CtxConfig, opts: SyncOptions = {}): SyncAction[] {
  const agentsPath = join(config.root, "AGENTS.md");
  if (!existsSync(agentsPath)) {
    throw new Error("AGENTS.md not found — run `ctxkit init` first");
  }
  const agents = readFileSync(agentsPath, "utf8");
  const actions: SyncAction[] = [];

  for (const [target, relFile] of resolveTargets(config)) {
    const dest = join(config.root, relFile);
    const exists = existsSync(dest);

    if (exists) {
      if (opts.link && isLinkToAgents(dest, agentsPath)) {
        actions.push({ target, path: relFile, action: "unchanged" });
        continue;
      }
      const current = readFileSync(dest, "utf8");
      if (!opts.link && current === expectedContent(agents)) {
        actions.push({ target, path: relFile, action: "unchanged" });
        continue;
      }
      // Never clobber a hand-written per-tool file unless forced.
      const ours = current.startsWith(GENERATED_MARK) || isLinkToAgents(dest, agentsPath);
      if (!ours && !opts.force) {
        actions.push({ target, path: relFile, action: "skipped-foreign" });
        continue;
      }
    }

    mkdirSync(dirname(dest), { recursive: true });
    if (opts.link) {
      if (exists) rmSync(dest);
      symlinkSync(relative(dirname(dest), agentsPath), dest);
      actions.push({ target, path: relFile, action: "linked" });
    } else {
      writeFileSync(dest, expectedContent(agents));
      actions.push({ target, path: relFile, action: "written" });
    }
  }
  return actions;
}

export interface SyncStatus {
  target: string;
  path: string;
  status: "ok" | "stale" | "missing";
}

export function checkSync(config: CtxConfig): SyncStatus[] {
  const agentsPath = join(config.root, "AGENTS.md");
  const agents = existsSync(agentsPath) ? readFileSync(agentsPath, "utf8") : null;
  const out: SyncStatus[] = [];
  for (const [target, relFile] of resolveTargets(config)) {
    const dest = join(config.root, relFile);
    if (!existsSync(dest)) {
      out.push({ target, path: relFile, status: "missing" });
      continue;
    }
    const upToDate =
      agents !== null &&
      (readFileSync(dest, "utf8") === expectedContent(agents) ||
        isLinkToAgents(dest, agentsPath));
    out.push({ target, path: relFile, status: upToDate ? "ok" : "stale" });
  }
  return out;
}
